; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
test_framework = googletest

[env:espwroom32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
	https://github.com/aserebryakov/arduino-cpp-components-library.git
	https://github.com/bblanchon/ArduinoJson.git
build_unflags = -std=gnu++11
build_flags = -std=gnu++2a -Wall -Wextra -Werror

[env:test_board]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -std=gnu++2a
test_build_src = true
test_framework = googletest
build_src_filter =
	+<**/EventFactory.*>
	+<**/RedAlertStateMachine.*>
lib_deps =
	skaygin/ArduinoNative@^0.1.4
	https://github.com/aserebryakov/arduino-cpp-components-library.git
	https://github.com/bblanchon/ArduinoJson.git

[env:test_native]
platform = native
build_flags = -std=gnu++2a
test_build_src = true
build_src_filter =
	+<**/EventFactory.*>
	+<**/RedAlertStateMachine.*>
lib_deps =
	skaygin/ArduinoNative@^0.1.4
	https://github.com/aserebryakov/arduino-cpp-components-library.git
	https://github.com/bblanchon/ArduinoJson.git